sudo: required
services:
  - docker
language: java
jdk: oraclejdk8
branches:
  only:
    - master
script:
  - ./gradlew test
  - deploy_url=$(now -p -n unicodetool-api -t $NOW_TOKEN)
  - ./gradlew endToEndTest -PdeploymentUrl=$deploy_url