sudo: required
services:
  - docker
language: java
jdk: oraclejdk8
branches:
  only:
    - master
before_script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
script:
  - ./ci/build.sh
  - ./ci/publish.sh